#!/bin/sh
# Start an HTTP server
python3 -m http.server --directory build &
PID=${!}

# Generate the PDF
electron-pdf \
    --landscape \
    http://localhost:8000 \
    build/index.pdf

# Kill the HTTP server
kill -9 ${PID}