name: Build PDF

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language:
          - en
          - es
          - pl

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build PDF
      run: |
        npm install
        /usr/bin/Xvfb $DISPLAY -ac -screen 0 1920x1280x24 &
        sleep 1
        npm run pdf:build
      env:
        VITE_LANGUAGE: ${{ matrix.language }}
        DISPLAY: ":99"

    - name: Upload job artifact
      uses: actions/upload-artifact@v2
      with:
        name: ev-faq
        path: build/ev-faq-${{ matrix.language }}.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ev-faq
        path: artifacts
    - name: Create GitHub release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: artifacts/*.pdf